<a href="https://colab.research.google.com/github/shanyageo1234/stress-detection-using-ML/blob/main/Spam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
import pandas as pd
import seaborn as sns

In [ ]:
from matplotlib import pyplot as plt
from sklearn.naive_bayes import BernoulliNB
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df=pd.read_csv('/content/drive/MyDrive/internship/spam.csv', encoding='latin1')

In [ ]:
#Visulizing dataset
df.head(10)

class                                            message Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   
5  spam  FreeMsg Hey there darling it's been 3 week's n...        NaN   
6   ham  Even my brother is not like to speak with me. ...        NaN   
7   ham  As per your request 'Melle Melle (Oru Minnamin...        NaN   
8  spam  WINNER!! As a valued network customer you have...        NaN   
9  spam  Had your mobile 11 months or more? U R entitle...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN  
5        NaN        NaN  
6        NaN        NaN  
7        NaN        NaN  
8        NaN        NaN  
9        NaN        NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   message     5572 non-null   object
 1   class       5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB


In [ ]:
df.isnull().sum()


message          0
class            0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

In [ ]:
df.describe()


message class  \
count                     5572  5572   
unique                    5169     2   
top     Sorry, I'll call later   ham   
freq                        30  4825   

                                               Unnamed: 2  \
count                                                  50   
unique                                                 43   
top      bt not his girlfrnd... G o o d n i g h t . . .@"   
freq                                                    3   

                   Unnamed: 3 Unnamed: 4  
count                      12          6  
unique                     10          5  
top      MK17 92H. 450Ppw 16"    GNT:-)"  
freq                        2          2

In [ ]:
df.shape

(5572, 5)

In [ ]:
np.unique(df['class'])

array(['ham', 'spam'], dtype=object)

In [ ]:
np.unique(df['message'])

array([' &lt;#&gt;  in mca. But not conform.',
       ' &lt;#&gt;  mins but i had to stop somewhere first.',
       ' &lt;DECIMAL&gt; m but its not a common car here so its better to buy from china or asia. Or if i find it less expensive. I.ll holla',
       ..., 'ÌÏ thk of wat to eat tonight.', 'ÌÏ v ma fan...',
       'ÌÏ wait 4 me in sch i finish ard 5..'], dtype=object)

In [ ]:
x=df["message"].values
y=df["class"].values

cv=CountVectorizer()

x=cv.fit_transform(x)
v=x.toarray()

print(v)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
first_col=df.pop('message')
df.insert(0,'message',first_col)
df

message class Unnamed: 2  \
0     Go until jurong point, crazy.. Available only ...   ham        NaN   
1                         Ok lar... Joking wif u oni...   ham        NaN   
2     Free entry in 2 a wkly comp to win FA Cup fina...  spam        NaN   
3     U dun say so early hor... U c already then say...   ham        NaN   
4     Nah I don't think he goes to usf, he lives aro...   ham        NaN   
...                                                 ...   ...        ...   
5567  This is the 2nd time we have tried 2 contact u...  spam        NaN   
5568              Will Ì_ b going to esplanade fr home?   ham        NaN   
5569  Pity, * was in mood for that. So...any other s...   ham        NaN   
5570  The guy did some bitching but I acted like i'd...   ham        NaN   
5571                         Rofl. Its true to its name   ham        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [ ]:
x_train=x[:4180]
y_train=y[:4180]


x_test=x[4180:]
y_test=y[4180:]


In [ ]:
bnb=BernoulliNB(binarize=0.0)
model=bnb.fit(x_train,y_train)

y_pred_train=bnb.predict(x_train)
y_pred_test=bnb.predict(x_test)


In [ ]:
print(bnb.score(x_train,y_train)*100)

print(bnb.score(x_test,y_test)*100)

98.70813397129187
98.20402298850574


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_train,y_pred_train))

              precision    recall  f1-score   support

         ham       0.99      1.00      0.99      3615
        spam       0.99      0.91      0.95       565

    accuracy                           0.99      4180
   macro avg       0.99      0.95      0.97      4180
weighted avg       0.99      0.99      0.99      4180



In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

         ham       0.98      1.00      0.99      1210
        spam       0.99      0.87      0.93       182

    accuracy                           0.98      1392
   macro avg       0.99      0.93      0.96      1392
weighted avg       0.98      0.98      0.98      1392



In [ ]:
#Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()

#fitting the model X_train, Y_train and train and test its accuracy and score
a= model.fit(x_train,y_train)
print("the train accuracy:",model.score(x_train, y_train)*100,'%')
print("the test accuracy:",model.score(x_test, y_test)*100,'%')
score = a.score(x_test, y_test)
print(score)

#import accuracy score, classification report and confusion matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix


# predict the model for its test and find its accuracy score, classification report and confusion matrix
prediction=model.predict(x_test)
print(f"Accuracy Score = {accuracy_score(y_test,prediction)*100}")
print(f"Confusion Matrix =\n {confusion_matrix(y_test,prediction)}")
print(f"Classification Report =\n {classification_report(y_test,prediction)}")

#find cunfusion matrix, specificity, sensetivity and time taken
#confusion matrix
cm= confusion_matrix(y_test,prediction)
print(f"Confusion Matrix =\n {confusion_matrix(y_test,prediction)}")
#specificity
specificity=(cm[1,1]/(cm[1,1]+cm[1,0])*100)
print("specificity", specificity)

#sensitivity
sensitivity=(cm[0,0]/(cm[0,0]+cm[0,1])*100)
print("sensitivity", sensitivity)

#time taken
import time
start=time.time_ns()
a
end=time.time_ns()
t= ((end- start)/1000000) #time in ms
print("time =", t)

the train accuracy: 100.0 %
the test accuracy: 96.62356321839081 %
0.9662356321839081
Accuracy Score = 96.62356321839081
Confusion Matrix =
 [[1193   17]
 [  30  152]]
Classification Report =
               precision    recall  f1-score   support

         ham       0.98      0.99      0.98      1210
        spam       0.90      0.84      0.87       182

    accuracy                           0.97      1392
   macro avg       0.94      0.91      0.92      1392
weighted avg       0.97      0.97      0.97      1392

Confusion Matrix =
 [[1193   17]
 [  30  152]]
specificity 83.51648351648352
sensitivity 98.59504132231405
time = 0.050808


In [ ]:
#Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
model= RandomForestClassifier()

#fitting the model X_train, Y_train and train and test its accuracy and score
model.fit(x_train,y_train)
print("the train accuracy:",model.score(x_train, y_train)*100,'%')
print("the test accuracy:",model.score(x_test, y_test)*100,'%')
score = a.score(x_test, y_test)
print(score)

#import accuracy score, classification report and confusion matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix


# predict the model for its test and find its accuracy score, classification report and confusion matrix
prediction=model.predict(x_test)
print(f"Accuracy Score = {accuracy_score(y_test,prediction)*100}")
print(f"Confusion Matrix =\n {confusion_matrix(y_test,prediction)}")
print(f"Classification Report =\n {classification_report(y_test,prediction)}")

# find confusion matrix, specificity, sensitivity and time taken
#confusion matrix
cm= confusion_matrix(y_test,prediction)
print(f"Confusion Matrix =\n {confusion_matrix(y_test,prediction)}")

#specificity
specificity=(cm[1,1]/(cm[1,1]+cm[1,0])*100)
print("specificity", specificity)

#sensitivity
sensitivity=(cm[0,0]/(cm[0,0]+cm[0,1])*100)
print("sensitivity", sensitivity)

#time taken
import time
start=time.time_ns()
a
end=time.time_ns()
t= ((end- start)/1000000) #time in ms
print("time =", t)

the train accuracy: 100.0 %
the test accuracy: 97.27011494252874 %
0.9662356321839081
Accuracy Score = 97.27011494252874
Confusion Matrix =
 [[1210    0]
 [  38  144]]
Classification Report =
               precision    recall  f1-score   support

         ham       0.97      1.00      0.98      1210
        spam       1.00      0.79      0.88       182

    accuracy                           0.97      1392
   macro avg       0.98      0.90      0.93      1392
weighted avg       0.97      0.97      0.97      1392

Confusion Matrix =
 [[1210    0]
 [  38  144]]
specificity 79.12087912087912
sensitivity 100.0
time = 0.049193
